# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Travis Swicegood's gif collection
email: gifs@domain51.com
description: > # this means to ignore newlines until "baseurl:"
  Decided to keep all of my gifs on GitHub. I'm eventually gonna make a site
  for exploring them too.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gifs.travisswicegood.com" # the base hostname & protocol for your site
twitter_username: tswicegood
github_username: tswicegood

# Build settings
markdown: kramdown
